function [lats, lons, names] = loadGpsMarkers(csvFilePath)
% LOADGPSMARKERS Load GPS markers from the .csv file generated by the
% Android app Map Marker.
%
% We have manually labeled the TX, together with trees in the measured
% area, using the app. This function is used to load the corresponding GPS
% data.
%
% Yaguang Zhang, Purdue, 03/30/2018

[lats, lons, names] = csvimport(csvFilePath, ...
    'columns', {'Latitude', 'Longitude', 'Title'});

end
% EOF