function [foliageDepth, losDist] = estimateFoliageDepthGps( ...
    srcGpsPt, dstGpsPt, vegAreas, VEG_AREA_IMG_META)
%ESTIMATEFOLIAGEDEPTHUTM Estimate the folaige depth between two GPS points
%(lat, lon) within the same UTM zone.
%
% Inputs:
%   - srcGpsPt, dstGpsPt
%     The source and destination points (2x1 vectors).
%   - vegAreas, VEG_AREA_IMG_META
%     The image structure reprenting the vegetation area and the meta
%     information for it, e.g. generated by:
%         9_GenerateVegAreas/generateVegAreas.m
%
% Output:
%   - foliageDepth
%     The estimated foliage depth in meters.
%
% Yaguang Zhang, Purdue, 08/13/2018

% Change input GPS points to UTM and verify that they are within the same
% zone.
[inputPtXs, inputPtYs, inputPtZones] = deg2utm( ...
    [srcGpsPt(1); dstGpsPt(1)], [srcGpsPt(2); dstGpsPt(2)]);
assert(strcmp(inputPtZones(1, :), inputPtZones(2, :)), ...
    'Input GPS points should be in the same UTM zone!');

% Calculate the LoS distance.
srcUtmPt = [inputPtXs(1); inputPtYs(1)];
dstUtmPt = [inputPtXs(2); inputPtYs(2)];
losDist = sqrt(sum((srcUtmPt-dstUtmPt).^2));

% Find the pixels corresponding to the input GPS points in the vegetation
% area image.
[srcPixPtX, srcPixPtY] = latLon2PixIndices(srcGpsPt(1), srcGpsPt(2), ...
    VEG_AREA_IMG_META.LAT_RANGE, VEG_AREA_IMG_META.LON_RANGE, ...
    VEG_AREA_IMG_META.IMG_RESOLUTION);
[dstPixPtX, dstPixPtY]  = latLon2PixIndices(dstGpsPt(1), dstGpsPt(2), ...
    VEG_AREA_IMG_META.LAT_RANGE, VEG_AREA_IMG_META.LON_RANGE, ...
    VEG_AREA_IMG_META.IMG_RESOLUTION);

% Find vegetation area pixels along the LoS line segment.
boolsInVegArea = improfile(vegAreas, ...
    [srcPixPtX, dstPixPtX], [srcPixPtY, dstPixPtY])>0;

% Calculate the in-vegetation-area ratio.
inVegAreaRatio = sum(boolsInVegArea)/length(boolsInVegArea);

% Estimate the LoS foliage depth accordingly.
foliageDepth = losDist.*inVegAreaRatio;

end
% EOF