function [ lats, lons, alts, gpsLogSamples ] = parseGpsLogs( gpsLogDirs )
%PARSEGPSLOGS Parse the GPS log files generated in the EARS measurement
%campaign.
%
% Input:
%   - gpsLogDirs
%     The dir object generated by rdir/dir indicating where the GPS log
%     files are.
% Output:
%   - lats, lons, alts
%     Column vectors with the (lat, lon, alt) fetched.
%   - gpsSamples
%     A column cell with fields generated according to the title line of
%     the file. Each field contains the corresponding value as a string.
%
% Yaguang Zhang, Purdue, 04/09/2018

% Parse the GPS log.
numGpsSamps = length(gpsLogDirs);
[lats, lons, alts] = deal(nan(numGpsSamps, 1));
gpsLogSamples = cell(numGpsSamps, 1);
for idxS = 1:numGpsSamps
    gpsLog = gpsLogDirs(idxS);
    [lat, lon, alt, gpsLogSample] = parseNmeaStr(gpsLog.gpsLocation);
    
    lats(idxS) = lat;
    lons(idxS) = lon;
    alts(idxS) = alt;
    gpsLogSamples{idxS} = gpsLogSample;
end

% EOF